version: 0.2

env:
  parameter-store:
    region: ""

phases:
  pre_build:
    commands:
      - printf "region - ${region}"
      - npm install
  build:
    commands:
      - npm run build

artifacts:
  base-directory: dist
  files:
    - '**/*'
