version: 0.2

phases:
  pre_build:
    commands:
      - printf "in buildspec_apache.yml"
      - aws ecr get-login --profile fa
  build:
    commands:
      - docker build -t 762858336698.dkr.ecr.us-west-2.amazonaws.com/chilyard-media-core-ui:latest .
      - docker tag chilyard-media-core-ui:latest 762858336698.dkr.ecr.us-west-2.amazonaws.com/chilyard-media-core-ui:latest
  post_build:
    commands:
      - docker push 762858336698.dkr.ecr.us-west-2.amazonaws.com/chilyard-media-core-ui:latest

artifacts:
  base-directory: dist
  files:
    - '**/*'
