version: 0.2

env:
  parameter-store:
    region: "us-west-2"

phases:
  pre_build:
    commands:
      - printf "in buildspec_apache.yml"
      - npm install
  build:
    commands:
      - npm run build

artifacts:
  base-directory: dist
  files:
    - '**/*'
