export default Object.assign(
  {
    campaignDetails: {
      utilizationTitle: 'Utilization',
      impressionsTitle: 'Impressions',
      impressionsMessage: 'The number of times client\'s ads were viewed.',
      cpmTitle: 'CPM (Cost per 1,000 Impressions)',
      cpmMessage: 'The average cost for 1,000 impressions.',
      ctrTitle: 'Click-Through Rate',
      ctrMessage: 'The percentage of times people saw client\'s ad and performed a click.',
      allClicksTitle: 'Clicks (All)',
      allClicksMessage: 'The number of clicks on client\'s ads.',
      frequencyTitle: 'Frequency',
      frequencyMessage: 'The average number of times each person saw client\'s ad.',
      reachTitle: 'Reach',
      reachMessage: 'The number of people who saw client\'s ads at least once. Reach is different from impressions, which may include multiple views of client\'s ads by the same people.',
      socialReachTitle: 'Social Reach',
      socialReachMessage: 'The number of people who saw client\'s ad when displayed with social information, which shows other Facebook friends who engaged with client\'s facebook Page or ad.',
      socialImpressionsTitle: 'Social Impressions',
      socialImpressionsMessage: 'The number of times client\'s ads were viewed when displayed with social information, which shows Facebook friends who engaged with client\'s Facebook Page or ad.',
      websiteClicksTitle: 'Website Clicks',
      websiteClicksMessage: 'The number of clicks to client\'s website.',
      buttonClicksTitle: 'Button Clicks',
      buttonClicksMessage: 'The number of times people clicked the call-to-action button on client\'s ad.',
      linkClicksTitle: 'Link Clicks',
      linkClicksMessage: 'The number of clicks on ad links to select destinations or experiences, on or off Facebook-owned properties.',
      socialClicksTitle: 'Social Clicks',
      socialClicksMessage: 'The number of clicks (all) when client\'s ad was displayed with social information, which shows other Facebook friends who engaged with client\'s Facebook Page or ad.',
      leadFormsTitle: 'Lead Forms Submitted',
      leadFormsMessage: 'The number of form responses submitted after people clicked on Facebook lead ads.',
      checkInsTitle: 'Check-Ins',
      checkInsMessage: 'The number of check-ins to client\'s Facebook Page that are attributed to client\'s ads. If client\'s page has a physical address associated with it, people can check in to client\'s Page when they update their status in their Facebook News Feed or Timeline.',
      postCommentsTitle: 'Post Comments',
      postCommentsMessage: 'The number of comments on client\'s ads.',
      postReactionsTitle: 'Post Reactions',
      postReactionsMessage: 'The number of reactions on client\'s ads. The reactions button on an ad allows people to share different reactions to its content: Like, Love, Haha, Wow, Sad or Angry.',
      postSharesTitle: 'Post Shares',
      postSharesMessage: 'The number of shares of client\'s ads. People can share client\'s ads or posts on their own or friend\'s Timelines, in groups and on their own Pages.',
      postEngagementTitle: 'Page Engagement',
      postEngagementMessage: 'The total number of actions that people took on client\'s Facebook Page and its posts, attributed to client\'s ads.',
      pageLikesTitle: 'Page Likes',
      pageLikesMessage: 'The number of likes of client\'s Facebook Page attributed to client\'s ads.',
      pageEngagementTitle: 'Page Engagement',
      pageEngagementMessage: 'The total number of actions that people took on client\'s Facebook Page and its posts, attributed to client\'s ads.'
    }
  }
);
